[package]
name = "draft-ietf-lamps-pq-composite-kem-04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elliptic-curve = "0.13.8"
k256 = "0.13.3"
ml-kem = "0.2.1"
p256 = "0.13.2"
p384 = "0.13.0"
p521 = "0.13.3"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
x25519-dalek = { version="2.0.1", features=["static_secrets"]}
